export enum RatingConstants {
    GET_RATINGS_REQUEST = 'GET_RATINGS_REQUEST',
    GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS',
    GET_RATINGS_FAILURE = 'GET_RATINGS_FAILURE',
    GET_RATINGS_OF_TEAM_REQUEST = 'GET_RATINGS_OF_TEAM_REQUEST',
    GET_RATINGS_OF_TEAM_SUCCESS = 'GET_RATINGS_OF_TEAM_SUCCESS',
    GET_RATINGS_OF_TEAM_FAILURE = 'GET_RATINGS_OF_TEAM_FAILURE',
    GET_RATINGS_OF_CHALLENGE_REQUEST = 'GET_RATINGS_OF_CHALLENGE_REQUEST',
    GET_RATINGS_OF_CHALLENGE_SUCCESS = 'GET_RATINGS_OF_CHALLENGE_SUCCESS',
    GET_RATINGS_OF_CHALLENGE_FAILURE = 'GET_RATINGS_OF_CHALLENGE_FAILURE',
  }