export enum ChallengeTypes {
    GET_CHALLENGES_REQUEST = 'GET_CHALLENGES_REQUEST',
    GET_CHALLENGES_SUCCESS = 'GET_CHALLENGES_SUCCESS',
    GET_CHALLENGES_FAILURE = 'GET_CHALLENGES_FAILURE',
    GET_CHALLENGE_REQUEST = 'GET_CHALLENGE_REQUEST',
    GET_CHALLENGE_SUCCESS = 'GET_CHALLENGE_SUCCESS',
    GET_CHALLENGE_FAILURE = 'GET_CHALLENGE_FAILURE',
    SELECT_FILE = 'SELECT_FILE',
    REMOVE_FILE = 'REMOVE_FILE'
}