export enum SubmissionTypes {
    GET_SUBMISSIONS_REQUEST = 'GET_SUBMISSIONS_REQUEST',
    GET_SUBMISSIONS_SUCCESS = 'GET_SUBMISSIONS_SUCCESS',
    GET_SUBMISSIONS_FAILURE = 'GET_SUBMISSIONS_FAILURE',
    GET_SUBMISSIONS_OF_TEAM_REQUEST = 'GET_SUBMISSIONS_OF_TEAM_REQUEST',
    GET_SUBMISSIONS_OF_TEAM_SUCCESS = 'GET_SUBMISSIONS_OF_TEAM_SUCCESS',
    GET_SUBMISSIONS_OF_TEAM_FAILURE = 'GET_SUBMISSIONS_OF_TEAM_FAILURE',
    GET_SUBMISSIONS_OF_CHALLENGE_REQUEST = 'GET_SUBMISSIONS_OF_CHALLENGE_REQUEST',
    GET_SUBMISSIONS_OF_CHALLENGE_SUCCESS = 'GET_SUBMISSIONS_OF_CHALLENGE_SUCCESS',
    GET_SUBMISSIONS_OF_CHALLENGE_FAILURE = 'GET_SUBMISSIONS_OF_CHALLENGE_FAILURE',
    SUBMIT_FILE_REQUEST = 'SUBMIT_FILE_REQUEST',
    SUBMIT_FILE_SUCCESS = 'SUBMIT_FILE_SUCCESS',
    SUBMIT_FILE_FAILURE = 'SUBMIT_FILE_FAILURE',
}
