export enum TeamTypes {
    GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST',
    GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS',
    GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE',
    GET_TEAMS_OF_CHALLENGE_REQUEST = 'GET_TEAMS_OF_CHALLENGE_REQUEST',
    GET_TEAMS_OF_CHALLENGE_SUCCESS = 'GET_TEAMS_OF_CHALLENGE_SUCCESS',
    GET_TEAMS_OF_CHALLENGE_FAILURE = 'GET_TEAMS_OF_CHALLENGE_FAILURE',
}