export enum UserTypes {
    GET_USERS_REQUEST = 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE = 'GET_USERS_FAILURE',
    GET_USERS_OF_TEAM_REQUEST = 'GET_USERS_OF_TEAM_REQUEST',
    GET_USERS_OF_TEAM_SUCCESS = 'GET_USERS_OF_TEAM_SUCCESS',
    GET_USERS_OF_TEAM_FAILURE = 'GET_USERS_OF_TEAM_FAILURE',
}